version: '3.8'

services:
  finsage:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
